steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
      '--build-arg', 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY',
      '--build-arg', 'VITE_TRANSLATE_KEY=$_VITE_TRANSLATE_KEY',
      '--build-arg', 'VITE_MAPS_KEY=$_VITE_MAPS_KEY',
      '-t', 'gcr.io/$PROJECT_ID/meramat-india','.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
      'gcr.io/$PROJECT_ID/meramat-india']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - meramat-india
      - --image=gcr.io/$PROJECT_ID/meramat-india
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi

images:
  - 'gcr.io/$PROJECT_ID/meramat-india'
