FROM node:20-alpine
ARG VITE_GEMINI_API_KEY
ARG VITE_TRANSLATE_KEY
ARG VITE_MAPS_KEY
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY
ENV VITE_TRANSLATE_KEY=$VITE_TRANSLATE_KEY
ENV VITE_MAPS_KEY=$VITE_MAPS_KEY
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 8080
ENV NODE_ENV=production
CMD ["node", "server.js"]
