export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
]

export const STATE_HELPLINES = {
  "Andaman and Nicobar Islands": "1950",
  "Andhra Pradesh": "1950",
  "Arunachal Pradesh": "1950",
  "Assam": "1950",
  "Bihar": "1950",
  "Chandigarh": "1950",
  "Chhattisgarh": "1950",
  "Dadra and Nagar Haveli and Daman and Diu": "1950",
  "Delhi": "1950",
  "Goa": "1950",
  "Gujarat": "1950",
  "Haryana": "1950",
  "Himachal Pradesh": "1950",
  "Jammu and Kashmir": "1950",
  "Jharkhand": "1950",
  "Karnataka": "1950",
  "Kerala": "1950",
  "Ladakh": "1950",
  "Lakshadweep": "1950",
  "Madhya Pradesh": "1950",
  "Maharashtra": "1950",
  "Manipur": "1950",
  "Meghalaya": "1950",
  "Mizoram": "1950",
  "Nagaland": "1950",
  "Odisha": "1950",
  "Puducherry": "1950",
  "Punjab": "1950",
  "Rajasthan": "1950",
  "Sikkim": "1950",
  "Tamil Nadu": "1950",
  "Telangana": "1950",
  "Tripura": "1950",
  "Uttar Pradesh": "1950",
  "Uttarakhand": "1950",
  "West Bengal": "1950",
}
